/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asscry;

import java.awt.FileDialog;
import java.io.File;
import javax.swing.JOptionPane;
import static org.bouncycastle.crypto.tls.SignatureAlgorithm.rsa;

/**
 *
 * @author duymi
 */
public class aesFrm extends javax.swing.JFrame {

    /**
     * Creates new form aesFrm
     */
    public aesFrm() {
        initComponents();
        this.setTitle("Giải thuật mã hóa AES dùng public key");
    }
    private clsAES aes;
    private AESGenetate aesKeygen;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFile = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfKey = new javax.swing.JTextField();
        btnMahoa = new javax.swing.JButton();
        btDecr = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnKey = new javax.swing.JButton();
        btnBw = new javax.swing.JButton();
        btKey = new javax.swing.JButton();
        cb128 = new javax.swing.JCheckBox();
        cb256 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Chọn một file để mã hóa:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Chọn Key :");

        btnMahoa.setText("Encrypt");
        btnMahoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMahoaActionPerformed(evt);
            }
        });

        btDecr.setText("Decrypt");
        btDecr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDecrActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnKey.setText("...");
        btnKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeyActionPerformed(evt);
            }
        });

        btnBw.setText("...");
        btnBw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBwActionPerformed(evt);
            }
        });

        btKey.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btKey.setText("Key Generation");
        btKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKeyActionPerformed(evt);
            }
        });

        cb128.setText("128 bit");

        cb256.setText("256 bit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMahoa, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btDecr, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFile, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfKey)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                            .addComponent(btKey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnBw, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                    .addComponent(btnKey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(cb128, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(cb256))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btKey, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cb128)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb256)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBw, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfKey, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKey, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDecr, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMahoa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMahoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMahoaActionPerformed
        // TODO add your handling code here:
        File directory = new File("");
        String outPut = directory.getAbsolutePath();

        aes = new clsAES();
        aes.aesEncrypt(tfKey.getText(), txtFile.getText(), outPut);
        JOptionPane.showMessageDialog(null, "Mã hóa thành công^^","Done",JOptionPane.INFORMATION_MESSAGE);
        

    }//GEN-LAST:event_btnMahoaActionPerformed

    private void btDecrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDecrActionPerformed
        // TODO add your handling code here:

        File directory = new File("");
        String outPut = directory.getAbsolutePath();

        aes = new clsAES();
        aes.aesDecrypt(tfKey.getText(), txtFile.getText(), outPut);
        JOptionPane.showMessageDialog(null, "Giải mã thành công^^","Done",JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_btDecrActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeyActionPerformed
        // TODO add your handling code here:
        File kfile = getFileDialogOpen("*.*");
        if(kfile== null)
        return;
        tfKey.setText(kfile.getAbsolutePath());
    }//GEN-LAST:event_btnKeyActionPerformed

    private void btnBwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBwActionPerformed
        // TODO add your handling code here:
        File file = getFileDialogOpen("*.*");
        if(file== null)
        return;
        txtFile.setText(file.getAbsolutePath());

    }//GEN-LAST:event_btnBwActionPerformed

    private void btKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKeyActionPerformed
        // TODO add your handling code here:
        aesKeygen= new AESGenetate();
        if(!cb128.isSelected() && !cb256.isSelected())
              JOptionPane.showMessageDialog(null, "Vui lòng chọn độ dài của key","Error",JOptionPane.ERROR_MESSAGE);
        else if(cb128.isSelected() && cb256.isSelected())
              JOptionPane.showMessageDialog(null, "chọn 1 trong 2 độ dài","Error",JOptionPane.ERROR_MESSAGE);
        else if(cb128.isSelected()){
        aesKeygen.saveKey(128);
        JOptionPane.showMessageDialog(null, "Tạo key thành coomg với 128 bit độ dài ^^","Done",JOptionPane.INFORMATION_MESSAGE);
        }
        else if (cb256.isSelected()){
        aesKeygen.saveKey(256);  
        JOptionPane.showMessageDialog(null, "Tạo key thành coomg với 256 bit độ dài ^^","Done",JOptionPane.INFORMATION_MESSAGE);
        
        } 

    }//GEN-LAST:event_btKeyActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDecr;
    private javax.swing.JButton btKey;
    private javax.swing.JButton btnBw;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnKey;
    private javax.swing.JButton btnMahoa;
    private javax.swing.JCheckBox cb128;
    private javax.swing.JCheckBox cb256;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tfKey;
    private javax.swing.JTextField txtFile;
    // End of variables declaration//GEN-END:variables

    private File getFileDialogOpen(String string) {
        FileDialog fd = new FileDialog(this, "Chọn file", FileDialog.LOAD);
        fd.setFile(string);
        fd.setVisible(true);
        if (fd.getFile()==null) {
            return null;
        }
        File file = new File(fd.getDirectory()+fd.getFile());
        if(!file.canRead()){
            JOptionPane.showMessageDialog(null, "File bạn chọn không thể đọc.",
                    "Error",JOptionPane.ERROR_MESSAGE);
            return null;
        }
        return file;
    }
    
}
