/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asscry;

import javax.swing.JOptionPane;

/**
 *
 * @author duymi
 */
public class mainFrm extends javax.swing.JFrame {

    /**
     * Creates new form mainFrm
     */
    public mainFrm() {
        initComponents();
        this.setTitle("Chọn giải thuật mã hóa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbClick = new javax.swing.JLabel();
        cbAES = new javax.swing.JCheckBox();
        cbDB = new javax.swing.JCheckBox();
        btOK = new javax.swing.JButton();
        btMd5 = new javax.swing.JButton();
        cbDES = new javax.swing.JCheckBox();
        mnbMain = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mnEdit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbClick.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbClick.setText("Chọn giải thuật mã hóa:");

        cbAES.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cbAES.setText("RSA");
        cbAES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAESActionPerformed(evt);
            }
        });

        cbDB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cbDB.setText("AES");

        btOK.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btOK.setText("Let's Go !");
        btOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOKActionPerformed(evt);
            }
        });

        btMd5.setText("MD5 Check Sum");
        btMd5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMd5ActionPerformed(evt);
            }
        });

        cbDES.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbDES.setText("DES");

        mnFile.setText("File");
        mnbMain.add(mnFile);

        mnEdit.setText("Edit");
        mnbMain.add(mnEdit);

        setJMenuBar(mnbMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbClick, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btMd5, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbAES)
                                .addComponent(cbDB, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(cbDES))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btOK, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbClick, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(cbDES)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbAES)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbDB)
                        .addGap(18, 18, 18)
                        .addComponent(btMd5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                    .addComponent(btOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOKActionPerformed
        // TODO add your handling code here:
       
        if(!cbAES.isSelected() && !cbDB.isSelected() && !cbDES.isSelected())
            JOptionPane.showMessageDialog(null, "Chọn một giải thuật^^","Error",JOptionPane.ERROR_MESSAGE);
        else if ((cbAES.isSelected()&&cbDB.isSelected()) || (cbDES.isSelected()&&cbDB.isSelected())|| (cbAES.isSelected()&&cbDES.isSelected()) ){
         JOptionPane.showMessageDialog(null, "Chỉ được chọn một giải thuật thôi^^","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(cbAES.isSelected()){
        rsaFrm demoRSA = new rsaFrm();
        demoRSA.setVisible(true);
        }
        else if(cbDB.isSelected()){
        aesFrm demoAES = new aesFrm();
        demoAES.setVisible(true);
        }
        else if(cbDES.isSelected()){
        desFrm demoDES = new desFrm();
        demoDES.setVisible(true);
        }
    }//GEN-LAST:event_btOKActionPerformed

    private void cbAESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAESActionPerformed

    private void btMd5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMd5ActionPerformed

        // TODO add your handling code here:
        md5Frm demoMD5 = new md5Frm();
        demoMD5.setVisible(true);
    }//GEN-LAST:event_btMd5ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMd5;
    private javax.swing.JButton btOK;
    private javax.swing.JCheckBox cbAES;
    private javax.swing.JCheckBox cbDB;
    private javax.swing.JCheckBox cbDES;
    private javax.swing.JLabel lbClick;
    private javax.swing.JMenu mnEdit;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenuBar mnbMain;
    // End of variables declaration//GEN-END:variables
}
